# PSM Enterprise - GitHub Actions CI/CD
# Layer 8: CI/CD Pipeline

name: PSM Enterprise CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # =====================
  # TEST & LINT
  # =====================
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # =====================
  # BUILD DOCKER IMAGES
  # =====================
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [gateway, processor]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # =====================
  # DEPLOY TO CLOUDFLARE
  # =====================
  deploy-cloudflare:
    name: Deploy Cloudflare Workers
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Worker
        run: |
          cd workers/cloudflare
          wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  # =====================
  # DEPLOY TO VERCEL
  # =====================
  deploy-vercel:
    name: Deploy Vercel Functions
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./functions/vercel

  # =====================
  # DEPLOY TO AWS
  # =====================
  deploy-aws:
    name: Deploy AWS Lambda
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with SAM
        run: |
          cd functions/aws
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

  # =====================
  # DEPLOY TO GCP
  # =====================
  deploy-gcp:
    name: Deploy GCP Functions
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy Function
        run: |
          cd functions/gcp
          gcloud functions deploy psm-api \
            --runtime nodejs20 \
            --trigger-http \
            --allow-unauthenticated \
            --region us-central1

  # =====================
  # DEPLOY INFRASTRUCTURE
  # =====================
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: [deploy-cloudflare, deploy-vercel, deploy-aws, deploy-gcp]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infrastructure/iac/terraform
          terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Plan
        run: |
          cd infrastructure/iac/terraform
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd infrastructure/iac/terraform
          terraform apply -auto-approve tfplan

  # =====================
  # DEPLOY TO ORACLE CLOUD
  # =====================
  deploy-oracle:
    name: Deploy to Oracle Cloud
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 163.192.105.31
          username: opc
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /opt/psm
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f

  # =====================
  # HEALTH CHECK
  # =====================
  health-check:
    name: Post-Deploy Health Check
    runs-on: ubuntu-latest
    needs: [deploy-cloudflare, deploy-vercel, deploy-oracle]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check Azure
        run: curl -f https://purplesquirrel.media || exit 1

      - name: Check Vercel
        run: curl -f https://vercel-dusky-pi.vercel.app/api/status || exit 1

      - name: Check Oracle
        run: curl -f http://163.192.105.31:8096/health || exit 1

      - name: Notify Success
        if: success()
        run: echo "All deployments successful!"

      - name: Notify Failure
        if: failure()
        run: echo "Deployment health check failed!"
